spring.application.name=student-admission-system
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/student_admission_db
spring.datasource.username=root
spring.datasource.password=root123

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-256-bit-secret-key-here-make-it-long-and-random-enough
jwt.expiration=86400000

file.upload-dir=uploads

spring.data.redis.host=touching-coyote-151984.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAlGwAAIgcDIxNDA2NWI5OTQzNmY0NjU1OGU3MDA5Y2VjZDZiOTY2Ng
spring.data.redis.ssl.enabled=true

razorpay.key.id=rzp_test_TIBrW8Q1Claav1
razorpay.key.secret=nBCUkhw2KU83wvIuK7Io61SU

server.port=${PORT:8080}